### ISSUE TITLE
Only shows loading screen

### ISSUE THREAD

**Issue by bradparks** [lightning-js/blits-example-app#2]
I tried to run this, and used a TMDB api key too, but all I get is this - no errors in the console, just that loading screen
Any suggestions?

<img width="546" alt="image" src="https://github.com/lightning-js/blits-example-app/assets/185477/693f761e-ab7a-4420-a295-096f19e57fdb">

<img width="476" alt="image" src="https://github.com/lightning-js/blits-example-app/assets/185477/da57d561-f03c-4ce8-8be1-034bd4a11156">

**Comment by michielvandergeest** [comment]
hey @bradparks I can see how you may have gotten confused by the eternal loading screen 😄 

Hopefully the extra explanation in the readme and first screen from PR #3 will avoid this in the future!

Closing this ticket as merged to master.
