### ISSUE TITLE
UI is not Responsive. Its Overflowing.. Why?

### ISSUE THREAD

**Issue by justForusee3** [lightning-js/blits-example-app#8]
When i'm bringing this ui in TV, its overflowing please tell me what to do.

**Comment by justForusee3** [comment]
![20231216_121441](https://github.com/lightning-js/blits-example-app/assets/125953355/c091c1eb-f85e-4f7d-ba9d-6c67ee36ca52)

**Comment by michielvandergeest** [comment]
Hi @justForusee3, thanks for bringing up this issue!

Looking at your photo, it seems like your device is running on 1280x720. The Blits Example App, however is configured for a 1920x1080 resolution.

To fix your issue, a new configuration option has been added to Blits, that allows you to specify the screen resolution. With this new update, when the setting is left blank, in most cases Blits will autodetect the screen resolution used and automatically adjusts for it.

I’ve just released a new version of Blits (v0.5.10) that includes this new functionality.

Let me know if that helps!

**Comment by justForusee3** [comment]
its working

**Comment by michielvandergeest** [comment]
Thanks for your feedback @justForusee3. Closing this issue now.
